### ISSUE TITLE
Even after installing all the dependencies still getting 'access denied' error 

### ISSUE THREAD

**Issue by Sophack** [Sophack/stunningCouscous#1]
PS C:\Users\saraf\ecomMod13\stunningCouscous\Develop> npm i sequelize

changed 1 package, and audited 131 packages in 1s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\saraf\ecomMod13\stunningCouscous\Develop> node seeds/index.js
C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:102
          throw new SequelizeErrors.ConnectionError(err);
                ^

ConnectionError [SequelizeConnectionError]: Server requests authentication using unknown plugin sha256_password. See TODO: add plugins doco here on how to configure or author authentication plugins.
    at ConnectionManager.connect (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:102:17)       
    at processTicksAndRejections (node:internal/process/task_queues:96:5)        
    at async ConnectionManager._connect (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:220:24)
    at async C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:174:32
    at async ConnectionManager.getConnection (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:197:7)
    at async C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\sequelize.js:305:26
    at async MySQLQueryInterface.dropTable (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\abstract\query-interface.js:111:5)
    at async Function.drop (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\model.js:1007:12)
    at async Sequelize.drop (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\sequelize.js:429:9)
    at async Sequelize.sync (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\sequelize.js:366:7) {
  parent: Error: Server requests authentication using unknown plugin sha256_password. See TODO: add plugins doco here on how to configure or author authentication plugins.
      at Object.authSwitchRequest (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\commands\auth_switch.js:46:11)
      at ClientHandshake.handshakeResult (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\commands\client_handshake.js:150:22)
      at ClientHandshake.execute (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\commands\command.js:39:22)
      at Connection.handlePacket (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:417:32)
      at PacketParser.onPacket (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9),
  original: Error: Server requests authentication using unknown plugin sha256_password. See TODO: add plugins doco here on how to configure or author authentication plugins.
      at Object.authSwitchRequest (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\commands\auth_switch.js:46:11)
      at ClientHandshake.handshakeResult (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\commands\client_handshake.js:150:22)
      at ClientHandshake.execute (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\commands\command.js:39:22)
      at Connection.handlePacket (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:417:32)
      at PacketParser.onPacket (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\packet_parser.js:75:16)
de_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
}
PS C:\Users\saraf\ecomMod13\stunningCouscous\Develop> npm i express

up to date, audited 131 packages in 596ms

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\saraf\ecomMod13\stunningCouscous\Develop> npm i mysql2

removed 6 packages, changed 5 packages, and audited 125 packages in 1s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\saraf\ecomMod13\stunningCouscous\Develop> node server.js
App listening on port 3001!
PS C:\Users\saraf\ecomMod13\stunningCouscous\Develop> npm run seed

> module-13-challenge-orm@1.0.0 seed
> node seeds/index.js

C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:94
          throw new SequelizeErrors.AccessDeniedError(err);
                ^

AccessDeniedError [SequelizeAccessDeniedError]: Access denied for user ''@'localhost' (using password: YES)
    at ConnectionManager.connect (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:94:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionManager._connect (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:220:24)
    at async C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:174:32
    at async ConnectionManager.getConnection (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:197:7)
    at async C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\sequelize.js:305:26
    at async MySQLQueryInterface.dropTable (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\dialects\abstract\query-interface.js:111:5)
    at async Function.drop (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\model.js:1007:12)
    at async Sequelize.drop (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\sequelize.js:429:9)
    at async Sequelize.sync (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\sequelize\lib\sequelize.js:366:7) {
  parent: Error: Access denied for user ''@'localhost' (using password: YES)
      at Packet.asError (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user ''@'localhost' (using password: YES)",
    sql: undefined
  },
  original: Error: Access denied for user ''@'localhost' (using password: YES)
      at Packet.asError (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\saraf\ecomMod13\stunningCouscous\Develop\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user ''@'localhost' (using password: YES)",
    sql: undefined
  }
}

**Comment by Sophack** [comment]
environment file was outside of the develop
